site_name: pgcrud
site_url: https://pgcrud.com
repo_url: https://github.com/dakivara/pgcrud

theme:
  name: material
  features:
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky

  palette:

    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - pgcrud: index.md
  - Getting Started:
    - Getting Started: getting-started/index.md
    - Demo Schema: getting-started/demo-schema.md
    - Cursor: getting-started/cursor.md
    - Create: getting-started/create.md
    - Read: getting-started/read.md
    - Update: getting-started/update.md
    - Delete: getting-started/delete.md
