name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install mkdocs-material
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install mkdocs-material

      - name: Build and deploy
        run: mkdocs gh-deploy --force
